services:
  postgresql:
    container_name: spark-postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: spark_db
      POSTGRES_USER: igli
      POSTGRES_PASSWORD: password
      PGDATA: data/postgres
    volumes:
      - postgresql:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgresql: