services:
  postgresql:
    container_name: spark-postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: spark_db
      POSTGRES_USER: igli
      POSTGRES_PASSWORD: password
      PGDATA: data/postgres
    volumes:
      - postgresql:/data/postgres
    ports:
      - "5432:5432"
  mysql:
    image: mysql:latest
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: igli
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  postgresql:
  mysql_data: