services:
  postgresql:
    container_name: spark-postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: spark_db
      POSTGRES_USER: igli
      POSTGRES_PASSWORD: password
      PGDATA: data/postgres
    volumes:
      - postgresql:/data/postgres
    ports:
      - "5432:5432"
  mysql:
    image: mysql:latest
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: igli
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  elasticsearch:
    image: elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./snapshots:/usr/share/elasticsearch/snapshots

volumes:
  postgresql:
  mysql_data:
  esdata: